"""Rubika messenger bot platform adapter.

Standalone ``RubikaClient`` built directly on ``peyk.transport``.
Does NOT inherit from ``TelegramLikeClient`` -- see
``docs/decisions.md`` for the R6 architectural conclusion, verified
against the official rubika.ir/botapi documentation.
"""

from .client import RubikaClient, RUBIKA_BASE_URL
from .errors import RubikaAPIError, error_for_envelope
from .models import (
    AuxData,
    Bot,
    BotCommand,
    Button,
    ButtonCalendar,
    ButtonCalendarTypeEnum,
    ButtonLocation,
    ButtonLocationTypeEnum,
    ButtonNumberPicker,
    ButtonSelection,
    ButtonSelectionGetEnum,
    ButtonSelectionItem,
    ButtonSelectionSearchEnum,
    ButtonSelectionTypeEnum,
    ButtonStringPicker,
    ButtonTextbox,
    ButtonTextboxTypeKeypadEnum,
    ButtonTextboxTypeLineEnum,
    ButtonTypeEnum,
    Chat,
    ChatKeypadTypeEnum,
    ChatTypeEnum,
    ContactMessage,
    EnumChatAccess,
    Event,
    EventJoinTypeEnum,
    EventTypeEnum,
    File,
    FileTypeEnum,
    ForwardedFrom,
    ForwardedFromEnum,
    GetUpdatesResult,
    InlineMessage,
    Keypad,
    KeypadRow,
    Location,
    Message,
    MessageSenderEnum,
    Metadata,
    MetadataPart,
    MetadataTypeEnum,
    Poll,
    PollStatus,
    PollStatusEnum,
    Sticker,
    Update,
    UpdateEndpointTypeEnum,
    UpdateTypeEnum,
)

__all__ = [
    "RubikaClient",
    "RUBIKA_BASE_URL",
    "RubikaAPIError",
    "error_for_envelope",
    # enums
    "ChatTypeEnum",
    "FileTypeEnum",
    "ForwardedFromEnum",
    "PollStatusEnum",
    "ButtonSelectionTypeEnum",
    "ButtonSelectionSearchEnum",
    "ButtonSelectionGetEnum",
    "ButtonCalendarTypeEnum",
    "ButtonTextboxTypeKeypadEnum",
    "ButtonTextboxTypeLineEnum",
    "ButtonLocationTypeEnum",
    "MessageSenderEnum",
    "UpdateTypeEnum",
    "ChatKeypadTypeEnum",
    "UpdateEndpointTypeEnum",
    "MetadataTypeEnum",
    "EnumChatAccess",
    "EventTypeEnum",
    "EventJoinTypeEnum",
    "ButtonTypeEnum",
    # models
    "AuxData",
    "Bot",
    "BotCommand",
    "Button",
    "ButtonCalendar",
    "ButtonLocation",
    "ButtonNumberPicker",
    "ButtonSelection",
    "ButtonSelectionItem",
    "ButtonStringPicker",
    "ButtonTextbox",
    "Chat",
    "ContactMessage",
    "Event",
    "File",
    "ForwardedFrom",
    "GetUpdatesResult",
    "InlineMessage",
    "Keypad",
    "KeypadRow",
    "Location",
    "Message",
    "Metadata",
    "MetadataPart",
    "Poll",
    "PollStatus",
    "Sticker",
    "Update",
]
